version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: CurrencyConverter.API/Dockerfile
    image: currency-converter-api
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      mode: replicated
    environment:
      # For production use: JWT_SECRET=your_secure_secret docker-compose up -d
      - ASPNETCORE_ENVIRONMENT=Staging
      - JWT_SECRET=${JWT_SECRET:-SuperSecureJwtKeyForStagingEnvironmentShouldBeAtLeast32Chars}
      - DefaultCurrencyProvider=Frankfurter
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - currency-converter-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
    networks:
      - currency-converter-network

networks:
  currency-converter-network:
    driver: bridge
